# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

transforms:
  train:
    - ${to_tensor}

  val:
    - ${to_tensor}

  test: ${transforms.val}
